// src/app/models/add-event.ts

export interface addEvent {
  eventId?: number; // Optional, as it's generated by the backend
  eventName: string;
  description: string;
  participantsCount?: number; // Optional, as it's calculated by the backend
  duration: number; 
  eventType: string;
  fundingSource: string;
  status: string;
}
